export const CartActionTypes = {
    TOGGLE_CART_HIDDEN_PROPERTY: 'TOGGLE_CART_HIDDEN_PROPERTY',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART', 
}