export const shopDataActionTypes = {
    FETCH_DATA_FROM_FIRESTORE_START: "FETCH_DATA_FROM_FIRESTORE_START",
    FETCH_DATA_FROM_FIRESTORE_SUCCESS: "FETCH_DATA_FROM_FIRESTORE_SUCCESS",
    FETCH_DATA_FROM_FIRESTORE_FAILURE: "FETCH_DATA_FROM_FIRESTORE_FAILURE",
}