export const UserActionTypes = {
    EMAIL_SIGN_UP_START: 'EMAIL_SIGN_UP_START',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_OUT_START: 'SIGN_OUT_START',
    GET_CURRENT_USER_FROM_STARTUP_START: 'GET_CURRENT_USER_FROM_STARTUP_START',
    EMAIL_SIGN_UP_SUCCESS: 'EMAIL_SIGN_UP_SUCCESS',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS', 
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE',
}